/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;

/**
 *
 * @author TEST
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        pnlStudent = new javax.swing.JPanel();
        lblUserStudent = new javax.swing.JLabel();
        lblPassStudent = new javax.swing.JLabel();
        txtUserStudent = new javax.swing.JTextField();
        btnLoginStudent = new javax.swing.JButton();
        txtPassStudent = new javax.swing.JPasswordField();
        btnStudent = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        lblUserAdmin = new javax.swing.JLabel();
        lblPassAdmin = new javax.swing.JLabel();
        txtUserAdmin = new javax.swing.JTextField();
        btnLoginAdmin = new javax.swing.JButton();
        txtPassAdmin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlStudent.setBorder(javax.swing.BorderFactory.createTitledBorder("Login - Student"));

        lblUserStudent.setText("Email:");

        lblPassStudent.setText("Password:");

        btnLoginStudent.setText("Login");
        btnLoginStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStudentLayout = new javax.swing.GroupLayout(pnlStudent);
        pnlStudent.setLayout(pnlStudentLayout);
        pnlStudentLayout.setHorizontalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassStudent)
                    .addComponent(lblUserStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(txtPassStudent))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoginStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlStudentLayout.setVerticalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserStudent)
                    .addComponent(txtUserStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassStudent)
                    .addComponent(txtPassStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnLoginStudent)
                .addGap(38, 38, 38))
        );

        btnStudent.setText("Student");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        lblQuestion.setText("Log as admin or student");

        pnlAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder("Login - Admin"));

        lblUserAdmin.setText("Email:");

        lblPassAdmin.setText("Password:");

        btnLoginAdmin.setText("Login");

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassAdmin)
                    .addComponent(lblUserAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(txtPassAdmin))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserAdmin)
                    .addComponent(txtUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassAdmin)
                    .addComponent(txtPassAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnLoginAdmin)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(478, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion)
                    .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(pnlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(145, Short.MAX_VALUE)
                    .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(87, 87, 87)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnLoginStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JButton btnLoginStudent;
    private javax.swing.JButton btnStudent;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel lblPassAdmin;
    private javax.swing.JLabel lblPassStudent;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblUserAdmin;
    private javax.swing.JLabel lblUserStudent;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JPasswordField txtPassAdmin;
    private javax.swing.JPasswordField txtPassStudent;
    private javax.swing.JTextField txtUserAdmin;
    private javax.swing.JTextField txtUserStudent;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnAdmin
     */
    public javax.swing.JButton getBtnAdmin() {
        return btnAdmin;
    }

    /**
     * @param btnAdmin the btnAdmin to set
     */
    public void setBtnAdmin(javax.swing.JButton btnAdmin) {
        this.btnAdmin = btnAdmin;
    }

    /**
     * @return the btnLoginAdmin
     */
    public javax.swing.JButton getBtnLoginAdmin() {
        return btnLoginAdmin;
    }

    /**
     * @param btnLoginAdmin the btnLoginAdmin to set
     */
    public void setBtnLoginAdmin(javax.swing.JButton btnLoginAdmin) {
        this.btnLoginAdmin = btnLoginAdmin;
    }

    /**
     * @return the btnLoginStudent
     */
    public javax.swing.JButton getBtnLoginStudent() {
        return btnLoginStudent;
    }

    /**
     * @param btnLoginStudent the btnLoginStudent to set
     */
    public void setBtnLoginStudent(javax.swing.JButton btnLoginStudent) {
        this.btnLoginStudent = btnLoginStudent;
    }

    /**
     * @return the btnStudent
     */
    public javax.swing.JButton getBtnStudent() {
        return btnStudent;
    }

    /**
     * @param btnStudent the btnStudent to set
     */
    public void setBtnStudent(javax.swing.JButton btnStudent) {
        this.btnStudent = btnStudent;
    }

    /**
     * @return the jOptionPane1
     */
    public javax.swing.JOptionPane getjOptionPane1() {
        return jOptionPane1;
    }

    /**
     * @param jOptionPane1 the jOptionPane1 to set
     */
    public void setjOptionPane1(javax.swing.JOptionPane jOptionPane1) {
        this.jOptionPane1 = jOptionPane1;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return pnlStudent;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.pnlStudent = jPanel1;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return pnlAdmin;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.pnlAdmin = jPanel3;
    }

    /**
     * @return the lblPassAdmin
     */
    public javax.swing.JLabel getLblPassAdmin() {
        return lblPassAdmin;
    }

    /**
     * @param lblPassAdmin the lblPassAdmin to set
     */
    public void setLblPassAdmin(javax.swing.JLabel lblPassAdmin) {
        this.lblPassAdmin = lblPassAdmin;
    }

    /**
     * @return the lblPassStudent
     */
    public javax.swing.JLabel getLblPassStudent() {
        return lblPassStudent;
    }

    /**
     * @param lblPassStudent the lblPassStudent to set
     */
    public void setLblPassStudent(javax.swing.JLabel lblPassStudent) {
        this.lblPassStudent = lblPassStudent;
    }

    /**
     * @return the lblQuestion
     */
    public javax.swing.JLabel getLblQuestion() {
        return lblQuestion;
    }

    /**
     * @param lblQuestion the lblQuestion to set
     */
    public void setLblQuestion(javax.swing.JLabel lblQuestion) {
        this.lblQuestion = lblQuestion;
    }

    /**
     * @return the lblUserAdmin
     */
    public javax.swing.JLabel getLblUserAdmin() {
        return lblUserAdmin;
    }

    /**
     * @param lblUserAdmin the lblUserAdmin to set
     */
    public void setLblUserAdmin(javax.swing.JLabel lblUserAdmin) {
        this.lblUserAdmin = lblUserAdmin;
    }

    /**
     * @return the lblUserStudent
     */
    public javax.swing.JLabel getLblUserStudent() {
        return lblUserStudent;
    }

    /**
     * @param lblUserStudent the lblUserStudent to set
     */
    public void setLblUserStudent(javax.swing.JLabel lblUserStudent) {
        this.lblUserStudent = lblUserStudent;
    }

    /**
     * @return the txtPassAdmin
     */
    public javax.swing.JPasswordField getTxtPassAdmin() {
        return txtPassAdmin;
    }

    /**
     * @param txtPassAdmin the txtPassAdmin to set
     */
    public void setTxtPassAdmin(javax.swing.JPasswordField txtPassAdmin) {
        this.txtPassAdmin = txtPassAdmin;
    }

    /**
     * @return the txtPassStudent
     */
    public javax.swing.JPasswordField getTxtPassStudent() {
        return txtPassStudent;
    }

    /**
     * @param txtPassStudent the txtPassStudent to set
     */
    public void setTxtPassStudent(javax.swing.JPasswordField txtPassStudent) {
        this.txtPassStudent = txtPassStudent;
    }

    /**
     * @return the txtUserAdmin
     */
    public javax.swing.JTextField getTxtUserAdmin() {
        return txtUserAdmin;
    }

    /**
     * @param txtUserAdmin the txtUserAdmin to set
     */
    public void setTxtUserAdmin(javax.swing.JTextField txtUserAdmin) {
        this.txtUserAdmin = txtUserAdmin;
    }

    /**
     * @return the txtUserStudent
     */
    public javax.swing.JTextField getTxtUserStudent() {
        return txtUserStudent;
    }

    /**
     * @param txtUserStudent the txtUserStudent to set
     */
    public void setTxtUserStudent(javax.swing.JTextField txtUserStudent) {
        this.txtUserStudent = txtUserStudent;
    }

    public void loginStudentAddActionListener(ActionListener actionListener) {
       
        btnLoginStudent.addActionListener(actionListener);
        
    }

    public void loginBtnStudentAddActionListener(ActionListener actionListener) {
        btnStudent.addActionListener(actionListener);
        
        
    }

    public void loginBtnAdminAddActionListener(ActionListener actionListener) {
        btnAdmin.addActionListener(actionListener);
    }

    public void addActionListenerLoginAdmin(ActionListener actionListener) {
        btnLoginAdmin.addActionListener(actionListener);
    }
}
