/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Vladimir
 */
public class FrmMainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainAdmin
     */
    public FrmMainAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiAdd = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiView = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/form/icon-planner_0.png"))); // NOI18N

        jMenu1.setText("Add New Subject");

        jmiAdd.setText("Add");
        jMenu1.add(jmiAdd);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View subjects");

        jmiView.setText("View");
        jMenu2.add(jmiView);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logout");

        jmiLogout.setText("Logout");
        jMenu3.add(jmiLogout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAdd;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiView;
    // End of variables declaration//GEN-END:variables

    public void addActionListenerView(ActionListener actionListener) {
        jmiView.addActionListener(actionListener);
    }

    public void addActionListenerAdd(ActionListener actionListener) {
        jmiAdd.addActionListener(actionListener);
    }

    public void addActionListenerLogout(ActionListener actionListener) {
        jmiLogout.addActionListener(actionListener);
    }
}
