/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import view.controller.MainStudentController;

/**
 *
 * @author Vladimir
 */
public class FrmMainStudent extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainStudent
     */
    public FrmMainStudent() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddNewPlan = new javax.swing.JMenuBar();
        jmPlans = new javax.swing.JMenu();
        jmiAddPlan = new javax.swing.JMenuItem();
        jmiViewPlans = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiLogout = new javax.swing.JMenuItem();
        jmAbout = new javax.swing.JMenu();
        jmiAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/form/icon-planner_0.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jmPlans.setText("Plans");

        jmiAddPlan.setText("AddPlan");
        jmPlans.add(jmiAddPlan);

        jmiViewPlans.setText("ViewPlans");
        jmiViewPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewPlansActionPerformed(evt);
            }
        });
        jmPlans.add(jmiViewPlans);

        AddNewPlan.add(jmPlans);

        jMenu1.setText("Logout");

        jmiLogout.setText("Logout");
        jMenu1.add(jmiLogout);

        AddNewPlan.add(jMenu1);

        jmAbout.setText("About");

        jmiAbout.setText("About");
        jmAbout.add(jmiAbout);

        AddNewPlan.add(jmAbout);

        setJMenuBar(AddNewPlan);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiViewPlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewPlansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiViewPlansActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AddNewPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmAbout;
    private javax.swing.JMenu jmPlans;
    private javax.swing.JMenuItem jmiAbout;
    private javax.swing.JMenuItem jmiAddPlan;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiViewPlans;
    // End of variables declaration//GEN-END:variables

    

    public void addActionListerAddNewPlan(ActionListener actionListener) {
        jmiAddPlan.addActionListener(actionListener);
    }

    public void addActionListenerView(ActionListener actionListener) {
        jmiViewPlans.addActionListener(actionListener);
    }

    public void addActionListenerAbout(ActionListener actionListener) {
        jmiAbout.addActionListener(actionListener);
    }

    public void addActionListenerLogout(ActionListener actionListener) {
        jmiLogout.addActionListener(actionListener);
    }
}
