/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;
import view.form.util.FormMode;

/**
 *
 * @author Vladimir
 */
public class FrmSubject extends javax.swing.JFrame {

    /**
     * Creates new form FrmSubject
     */
    public FrmSubject() {
        initComponents();
    }

    public FrmSubject(FormMode fm) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjects = new javax.swing.JTable();
        btnAddProj = new javax.swing.JButton();
        btnRemoveProj = new javax.swing.JButton();
        btnEditProj = new javax.swing.JButton();
        lblDeadline = new javax.swing.JLabel();
        txtSemester = new javax.swing.JTextField();
        lblPoints = new javax.swing.JLabel();
        txtEspb = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnEnable = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Name:");

        lblDescription.setText("Description:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Projects"));

        tblProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProjects);

        btnAddProj.setText("Add project");

        btnRemoveProj.setText("Remove");

        btnEditProj.setText("Edit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddProj, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnRemoveProj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditProj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAddProj, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditProj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveProj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lblDeadline.setText("Semester:");

        lblPoints.setText("ESPB:");

        btnEdit.setText("Save edit");

        btnRemove.setText("Remove this subject");

        btnEnable.setText("Enable changes");

        btnSave.setText("Save");

        btncancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblDescription))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeadline)
                            .addComponent(lblPoints))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSemester)
                            .addComponent(txtEspb, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(btnEnable, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeadline)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoints)
                    .addComponent(txtEspb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEnable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProj;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditProj;
    private javax.swing.JButton btnEnable;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemoveProj;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btncancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeadline;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JTable tblProjects;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtEspb;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSemester;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnAddProj
     */
    public javax.swing.JButton getBtnAddProj() {
        return btnAddProj;
    }

    /**
     * @param btnAddProj the btnAddProj to set
     */
    public void setBtnAddProj(javax.swing.JButton btnAddProj) {
        this.btnAddProj = btnAddProj;
    }

    /**
     * @return the btnEdit
     */
    public javax.swing.JButton getBtnEdit() {
        return btnEdit;
    }

    /**
     * @param btnEdit the btnEdit to set
     */
    public void setBtnEdit(javax.swing.JButton btnEdit) {
        this.btnEdit = btnEdit;
    }

    /**
     * @return the btnEditProj
     */
    public javax.swing.JButton getBtnEditProj() {
        return btnEditProj;
    }

    /**
     * @param btnEditProj the btnEditProj to set
     */
    public void setBtnEditProj(javax.swing.JButton btnEditProj) {
        this.btnEditProj = btnEditProj;
    }

    /**
     * @return the btnEnable
     */
    public javax.swing.JButton getBtnEnable() {
        return btnEnable;
    }

    /**
     * @param btnEnable the btnEnable to set
     */
    public void setBtnEnable(javax.swing.JButton btnEnable) {
        this.btnEnable = btnEnable;
    }

    /**
     * @return the btnRemove
     */
    public javax.swing.JButton getBtnRemove() {
        return btnRemove;
    }

    /**
     * @param btnRemove the btnRemove to set
     */
    public void setBtnRemove(javax.swing.JButton btnRemove) {
        this.btnRemove = btnRemove;
    }

    /**
     * @return the btnRemoveProj
     */
    public javax.swing.JButton getBtnRemoveProj() {
        return btnRemoveProj;
    }

    /**
     * @param btnRemoveProj the btnRemoveProj to set
     */
    public void setBtnRemoveProj(javax.swing.JButton btnRemoveProj) {
        this.btnRemoveProj = btnRemoveProj;
    }

    /**
     * @return the btnSave
     */
    public javax.swing.JButton getBtnSave() {
        return btnSave;
    }

    /**
     * @param btnSave the btnSave to set
     */
    public void setBtnSave(javax.swing.JButton btnSave) {
        this.btnSave = btnSave;
    }

    /**
     * @return the btncancel
     */
    public javax.swing.JButton getBtncancel() {
        return btncancel;
    }

    /**
     * @param btncancel the btncancel to set
     */
    public void setBtncancel(javax.swing.JButton btncancel) {
        this.btncancel = btncancel;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the lblDeadline
     */
    public javax.swing.JLabel getLblDeadline() {
        return lblDeadline;
    }

    /**
     * @param lblDeadline the lblDeadline to set
     */
    public void setLblDeadline(javax.swing.JLabel lblDeadline) {
        this.lblDeadline = lblDeadline;
    }

    /**
     * @return the lblDescription
     */
    public javax.swing.JLabel getLblDescription() {
        return lblDescription;
    }

    /**
     * @param lblDescription the lblDescription to set
     */
    public void setLblDescription(javax.swing.JLabel lblDescription) {
        this.lblDescription = lblDescription;
    }

    /**
     * @return the lblName
     */
    public javax.swing.JLabel getLblName() {
        return lblName;
    }

    /**
     * @param lblName the lblName to set
     */
    public void setLblName(javax.swing.JLabel lblName) {
        this.lblName = lblName;
    }

    /**
     * @return the lblPoints
     */
    public javax.swing.JLabel getLblPoints() {
        return lblPoints;
    }

    /**
     * @param lblPoints the lblPoints to set
     */
    public void setLblPoints(javax.swing.JLabel lblPoints) {
        this.lblPoints = lblPoints;
    }

    /**
     * @return the tblProjects
     */
    public javax.swing.JTable getTblProjects() {
        return tblProjects;
    }

    /**
     * @param tblProjects the tblProjects to set
     */
    public void setTblProjects(javax.swing.JTable tblProjects) {
        this.tblProjects = tblProjects;
    }

    /**
     * @return the txtDescription
     */
    public javax.swing.JTextField getTxtDescription() {
        return txtDescription;
    }

    /**
     * @param txtDescription the txtDescription to set
     */
    public void setTxtDescription(javax.swing.JTextField txtDescription) {
        this.txtDescription = txtDescription;
    }

    /**
     * @return the txtEspb
     */
    public javax.swing.JTextField getTxtEspb() {
        return txtEspb;
    }

    /**
     * @param txtEspb the txtEspb to set
     */
    public void setTxtEspb(javax.swing.JTextField txtEspb) {
        this.txtEspb = txtEspb;
    }

    /**
     * @return the txtName
     */
    public javax.swing.JTextField getTxtName() {
        return txtName;
    }

    /**
     * @param txtName the txtName to set
     */
    public void setTxtName(javax.swing.JTextField txtName) {
        this.txtName = txtName;
    }

    /**
     * @return the txtSemester
     */
    public javax.swing.JTextField getTxtSemester() {
        return txtSemester;
    }

    /**
     * @param txtSemester the txtSemester to set
     */
    public void setTxtSemester(javax.swing.JTextField txtSemester) {
        this.txtSemester = txtSemester;
    }

    public void addActionListenerAddProject(ActionListener actionListener) {
        btnAddProj.addActionListener(actionListener);
    }

    public void addActionListenerEditProject(ActionListener actionListener) {
        btnEditProj.addActionListener(actionListener);
    }

    public void addActionListenerRemove(ActionListener actionListener) {
        btnRemoveProj.addActionListener(actionListener);
    }

    public void addActionListenerCancel(ActionListener actionListener) {
        btncancel.addActionListener(actionListener);
    }

    public void addActionListenerSave(ActionListener actionListener) {
        btnSave.addActionListener(actionListener);
    }

    public void addActionListenerEnable(ActionListener actionListener) {
        btnEnable.addActionListener(actionListener);
    }

    public void addActionListenerEdit(ActionListener actionListener) {
        btnEdit.addActionListener(actionListener);
    }

    public void addActionListenerRemoveSubject(ActionListener actionListener) {
        btnRemove.addActionListener(actionListener);
    }
}
